include:
  - project: wiley-sons/tc-gitlab-templates
    file: autodevops-gradle.gitlab-ci.yml
    ref: latest_image

variables:
  APP_NAME: eventhub
  AUTO_DEVOPS_DEPLOY_DEBUG: "true"
  TEST_DISABLED: "true"

build:
  stage: build
  image: 'registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image:v1.12.0'
  tags:
    - dev
  variables:
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2
    BP_GRADLE_BUILT_ARTIFACT: "app/build/libs/*.[jw]ar"
    BP_GRADLE_BUILD_ARGUMENTS: ":app:bootJar"
    AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: "BP_GRADLE_BUILT_ARTIFACT,BP_GRADLE_BUILD_ARGUMENTS"
#    BP_JVM_VERSION: "11.*"
#    BP_GRADLE_BUILT_ARTIFACT: "app/build/libs/*.[jw]ar"
#    BP_GRADLE_BUILD_ARGUMENTS: ":app:bootJar"
#    AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: "BP_GRADLE_BUILT_ARTIFACT,BP_GRADLE_BUILD_ARGUMENTS,BP_JVM_VERSION"
  services:
    - name: 'artifactory.aws.wiley.com/docker/tc/docker:${DOCKER_VERSION}-dind'
      command: ['--tls=false', '--host=tcp://0.0.0.0:2375']
  before_script:
    - export
    - |
      export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
      export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-v$(cat VERSION)}
  script:
    - /build/build.sh
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'  # run on default branch
    - if: '$CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'  # run on default branch pull requests

review:
  variables:
    KUBE_NAMESPACE: epdcs-review
    K8S_SECRET_SPRING_PROFILES_ACTIVE: review
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-review.yaml


review-integrationtest:
  when: manual
  image: artifactory.aws.wiley.com/docker/openjdk:11-jdk
  extends: .review-integration-test
  variables:
    ENVIRONMENT_HOST: environment_url.txt
  script:
    - ./gradlew :acceptance-test:acceptanceTest

dev:
  variables:
    KUBE_NAMESPACE: epdcs-dev
    K8S_SECRET_SPRING_PROFILES_ACTIVE: dev
    KUBE_INGRESS_BASE_DOMAIN: dev.tc.private.wiley.host
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-dev.yaml

dev-integrationtest:
  when: manual
  image: artifactory.aws.wiley.com/docker/openjdk:11-jdk
  variables:
    APP_ENVIRONMENT: dev
  allow_failure: true
  extends: .dev-integration-test
  script:
    - ./gradlew :acceptance-test:acceptanceTest

qa:
  variables:
    KUBE_NAMESPACE: epdcs-qa
    K8S_SECRET_SPRING_PROFILES_ACTIVE: qa
    KUBE_INGRESS_BASE_DOMAIN: qa.tc.wiley.host
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-qa.yaml

qa-integrationtest:
  when: manual
  image: artifactory.aws.wiley.com/docker/openjdk:11-jdk
  variables:
    APP_ENVIRONMENT: qa
  allow_failure: true
  extends: .qa-integration-test
  script:
    - ./gradlew :acceptance-test:acceptanceTest